config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  post 'tasks/create'
  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.new
    @tasks = Task.all
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path
    else
      flash.now['danger'] = t('defaults.messages.not_created', item: Task.model_name.human)
    end
  end 

  private

  def task_params
    params.require(:task).permit(:name, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WakeYouUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.slim
form_with model: task, local: true do |f|
f.textarea :name
f.submit

app/views/tasks/index.html.slim
h3= Date.today
= form_with model: @task, url: tasks_create_path, local: true do |f|
  = f.text_field :name
  = f.submit '登録'
p 今日のやること
- @tasks.each do |task|
  = task.name